import { SAMPLE_PROJECT_MEMBERS } from "../project-members/sample-data"
import { SAMPLE_PROJECTS } from "../projects/sample-data"
import {
  TASK_PRIORITY_CATALOG,
  TASK_STATUS_CATALOG,
  TASK_TYPE_CATALOG,
} from "./constants"
import type { ITask } from "./types"

export const SAMPLE_TASK_TYPES = TASK_TYPE_CATALOG
export const SAMPLE_TASK_STATUSES = TASK_STATUS_CATALOG
export const SAMPLE_TASK_PRIORITIES = TASK_PRIORITY_CATALOG

export const SAMPLE_TASKS: ITask[] = [
  {
    id: "task-1",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Implement Login Flow",
    description: "Design and implement the user authentication system using Auth.js.",
    type: "feature",
    status: "in-progress",
    priority: "high",
    assigneeId: SAMPLE_PROJECT_MEMBERS[0].id,
    assignee: SAMPLE_PROJECT_MEMBERS[0],
    startDate: new Date("2026-03-31T08:00:00.0Z"),
    dueDate: new Date("2026-04-05T17:00:00.0Z"),
    estimatedHours: 12,
    actualHours: 4,
    createdAt: new Date("2026-03-31T10:01:00.000Z"),
    updatedAt: new Date("2026-03-31T10:01:00.000Z"),
  },
  {
    id: "task-2",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Setup Project Infrastructure",
    description: "Initialize the repository, configure linting, and setup CI/CD.",
    type: "task",
    status: "done",
    priority: "medium",
    assigneeId: SAMPLE_PROJECT_MEMBERS[1].id,
    assignee: SAMPLE_PROJECT_MEMBERS[1],
    startDate: new Date("2026-03-30T09:00:00.0Z"),
    dueDate: new Date("2026-03-31T17:00:00.0Z"),
    estimatedHours: 8,
    actualHours: 6,
    createdAt: new Date("2026-03-30T10:01:00.000Z"),
    updatedAt: new Date("2026-03-31T09:30:00.000Z"),
  },
  {
    id: "task-3",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Fix Navigation Sidebar Bug",
    description: "Sidebar collapses unexpectedly on mobile devices.",
    type: "bug",
    status: "blocked",
    priority: "highest",
    assigneeId: SAMPLE_PROJECT_MEMBERS[0].id,
    assignee: SAMPLE_PROJECT_MEMBERS[0],
    dueDate: new Date("2026-04-01T12:00:00.0Z"),
    estimatedHours: 4,
    createdAt: new Date("2026-03-31T11:00:00.000Z"),
    updatedAt: new Date("2026-03-31T11:00:00.000Z"),
  },
  {
    id: "task-4",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Draft Project Documentation",
    description: "Create a comprehensive README.md and contributing guidelines.",
    type: "epic",
    status: "in-review",
    priority: "low",
    assigneeId: SAMPLE_PROJECT_MEMBERS[1].id,
    assignee: SAMPLE_PROJECT_MEMBERS[1],
    startDate: new Date("2026-04-01T13:00:00.0Z"),
    dueDate: new Date("2026-04-03T17:00:00.0Z"),
    estimatedHours: 6,
    createdAt: new Date("2026-03-31T15:20:00.000Z"),
    updatedAt: new Date("2026-03-31T15:20:00.000Z"),
  },
  // --- New Tasks ---
  {
    id: "task-5",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Design Dashboard Mockups",
    description: "Create high-fidelity wireframes for the main project dashboard.",
    type: "feature",
    status: "in-progress",
    priority: "medium",
    assigneeId: SAMPLE_PROJECT_MEMBERS[0].id,
    assignee: SAMPLE_PROJECT_MEMBERS[0],
    estimatedHours: 10,
    createdAt: new Date("2026-04-01T09:00:00.0Z"),
    updatedAt: new Date("2026-04-01T09:00:00.0Z"),
  },
  {
    id: "task-6",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Refactor API Layer",
    description: "Simplify the fetch logic and add caching header support.",
    type: "task",
    status: "todo",
    priority: "high",
    assigneeId: SAMPLE_PROJECT_MEMBERS[1].id,
    assignee: SAMPLE_PROJECT_MEMBERS[1],
    estimatedHours: 8,
    createdAt: new Date("2026-04-01T10:00:00.0Z"),
    updatedAt: new Date("2026-04-01T10:00:00.0Z"),
  },
  {
    id: "task-7",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Fix Memory Leak in Timers",
    description: "Timer functions are not properly cleared on unmount.",
    type: "bug",
    status: "todo",
    priority: "highest",
    assigneeId: SAMPLE_PROJECT_MEMBERS[0].id,
    assignee: SAMPLE_PROJECT_MEMBERS[0],
    estimatedHours: 4,
    createdAt: new Date("2026-04-01T11:00:00.0Z"),
    updatedAt: new Date("2026-04-01T11:00:00.0Z"),
  },
  {
    id: "task-8",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "User Profile Settings",
    description: "Allow users to update their bio and profile picture.",
    type: "feature",
    status: "backlog",
    priority: "low",
    assigneeId: SAMPLE_PROJECT_MEMBERS[1].id,
    assignee: SAMPLE_PROJECT_MEMBERS[1],
    estimatedHours: 6,
    createdAt: new Date("2026-04-01T12:00:00.0Z"),
    updatedAt: new Date("2026-04-01T12:00:00.0Z"),
  },
  {
    id: "task-9",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "CI/CD Pipeline Optimization",
    description: "Reduce build times by caching node_modules.",
    type: "task",
    status: "in-review",
    priority: "medium",
    assigneeId: SAMPLE_PROJECT_MEMBERS[0].id,
    assignee: SAMPLE_PROJECT_MEMBERS[0],
    estimatedHours: 4,
    createdAt: new Date("2026-04-01T13:00:00.0Z"),
    updatedAt: new Date("2026-04-01T13:00:00.0Z"),
  },
  {
    id: "task-10",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Data Export Feature",
    description: "Export project tasks to CSV and PDF formats.",
    type: "feature",
    status: "todo",
    priority: "high",
    assigneeId: SAMPLE_PROJECT_MEMBERS[1].id,
    assignee: SAMPLE_PROJECT_MEMBERS[1],
    estimatedHours: 12,
    createdAt: new Date("2026-04-01T14:00:00.0Z"),
    updatedAt: new Date("2026-04-01T14:00:00.0Z"),
  },
  {
    id: "task-11",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Dark Mode Support",
    description: "Implement a customizable theme provider with dark mode options.",
    type: "feature",
    status: "done",
    priority: "low",
    assigneeId: SAMPLE_PROJECT_MEMBERS[0].id,
    assignee: SAMPLE_PROJECT_MEMBERS[0],
    estimatedHours: 8,
    createdAt: new Date("2026-04-02T09:00:00.0Z"),
    updatedAt: new Date("2026-04-03T10:00:00.0Z"),
  },
  {
    id: "task-12",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Mobile Layout Refinement",
    description: "Adjust padding and font sizes for better mobile accessibility.",
    type: "bug",
    status: "in-progress",
    priority: "medium",
    assigneeId: SAMPLE_PROJECT_MEMBERS[1].id,
    assignee: SAMPLE_PROJECT_MEMBERS[1],
    estimatedHours: 6,
    createdAt: new Date("2026-04-02T10:00:00.0Z"),
    updatedAt: new Date("2026-04-02T10:00:00.0Z"),
  },
  {
    id: "task-13",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Email Notifications Setup",
    description: "Configure SendGrid for automatic task assignment emails.",
    type: "task",
    status: "backlog",
    priority: "medium",
    assigneeId: SAMPLE_PROJECT_MEMBERS[0].id,
    assignee: SAMPLE_PROJECT_MEMBERS[0],
    estimatedHours: 10,
    createdAt: new Date("2026-04-02T11:00:00.0Z"),
    updatedAt: new Date("2026-04-02T11:00:00.0Z"),
  },
  {
    id: "task-14",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Search Functionality",
    description: "Global search across projects and tasks with fuzzy matching.",
    type: "epic",
    status: "todo",
    priority: "high",
    assigneeId: SAMPLE_PROJECT_MEMBERS[1].id,
    assignee: SAMPLE_PROJECT_MEMBERS[1],
    estimatedHours: 20,
    createdAt: new Date("2026-04-02T12:00:00.0Z"),
    updatedAt: new Date("2026-04-02T12:00:00.0Z"),
  },
  {
    id: "task-15",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Role-Based Access Control",
    description: "Define permissions for Admin, Member, and Viewer roles.",
    type: "feature",
    status: "blocked",
    priority: "highest",
    assigneeId: SAMPLE_PROJECT_MEMBERS[0].id,
    assignee: SAMPLE_PROJECT_MEMBERS[0],
    estimatedHours: 15,
    createdAt: new Date("2026-04-02T13:00:00.0Z"),
    updatedAt: new Date("2026-04-02T13:00:00.0Z"),
  },
  {
    id: "task-16",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "API Rate Limiting",
    description: "Limit requests per IP to prevent service abuse.",
    type: "task",
    status: "todo",
    priority: "medium",
    assigneeId: SAMPLE_PROJECT_MEMBERS[1].id,
    assignee: SAMPLE_PROJECT_MEMBERS[1],
    estimatedHours: 5,
    createdAt: new Date("2026-04-03T09:00:00.0Z"),
    updatedAt: new Date("2026-04-03T09:00:00.0Z"),
  },
  {
    id: "task-17",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Fix Styling in Modal",
    description: "Button colors in the task creation modal are inconsistent.",
    type: "bug",
    status: "done",
    priority: "lowest",
    assigneeId: SAMPLE_PROJECT_MEMBERS[0].id,
    assignee: SAMPLE_PROJECT_MEMBERS[0],
    estimatedHours: 2,
    createdAt: new Date("2026-04-03T10:00:00.0Z"),
    updatedAt: new Date("2026-04-04T11:00:00.0Z"),
  },
  {
    id: "task-18",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Add Tooltips to Icons",
    description: "Explain the meaning of various status and type icons.",
    type: "feature",
    status: "todo",
    priority: "lowest",
    assigneeId: SAMPLE_PROJECT_MEMBERS[1].id,
    assignee: SAMPLE_PROJECT_MEMBERS[1],
    estimatedHours: 3,
    createdAt: new Date("2026-04-03T11:00:00.0Z"),
    updatedAt: new Date("2026-04-03T11:00:00.0Z"),
  },
  {
    id: "task-19",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Keyboard Shortcuts System",
    description: "Implement hotkeys for common actions like creating a task.",
    type: "feature",
    status: "todo",
    priority: "medium",
    assigneeId: SAMPLE_PROJECT_MEMBERS[0].id,
    assignee: SAMPLE_PROJECT_MEMBERS[0],
    estimatedHours: 8,
    createdAt: new Date("2026-04-03T12:00:00.0Z"),
    updatedAt: new Date("2026-04-03T12:00:00.0Z"),
  },
  {
    id: "task-20",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Performance Monitoring Setup",
    description: "Integrate Sentry or New Relic for error tracking and latency metrics.",
    type: "task",
    status: "backlog",
    priority: "low",
    assigneeId: SAMPLE_PROJECT_MEMBERS[1].id,
    assignee: SAMPLE_PROJECT_MEMBERS[1],
    estimatedHours: 6,
    createdAt: new Date("2026-04-03T13:00:00.0Z"),
    updatedAt: new Date("2026-04-03T13:00:00.0Z"),
  }
]