import { SAMPLE_PROJECT_MEMBERS } from "../project-members/sample-data"
import { SAMPLE_PROJECTS } from "../projects/sample-data"
import type { ITask, ITaskPriority, ITaskStatus, ITaskType } from "./types"

export const SAMPLE_TASK_TYPES: ITaskType[] = [
  {
    id: "type-feature",
    name: "Feature",
    color: "#3b82f6",
    icon: "lucide:sparkles",
    scope: "system",
    isMilestone: false,
    isApproval: false,
    isDefault: true,
    createdAt: new Date("2026-03-31T10:01:00.000Z"),
  },
  {
    id: "type-bug",
    name: "Bug",
    color: "#ef4444",
    icon: "lucide:bug",
    scope: "system",
    isMilestone: false,
    isApproval: false,
    isDefault: false,
    createdAt: new Date("2026-03-31T10:01:00.000Z"),
  },
  {
    id: "type-improvement",
    name: "Improvement",
    color: "#10b981",
    icon: "lucide:trending-up",
    scope: "system",
    isMilestone: false,
    isApproval: false,
    isDefault: false,
    createdAt: new Date("2026-03-31T10:01:00.000Z"),
  },
]

export const SAMPLE_TASK_STATUSES: ITaskStatus[] = [
  {
    id: "status-todo",
    name: "To Do",
    color: "#64748b",
    scope: "system",
    isDefault: true,
    isCompleted: false,
    order: 1,
    createdAt: new Date("2026-03-31T10:01:00.000Z"),
  },
  {
    id: "status-in-progress",
    name: "In Progress",
    color: "#0ea5e9",
    scope: "system",
    isDefault: false,
    isCompleted: false,
    order: 2,
    createdAt: new Date("2026-03-31T10:01:00.000Z"),
  },
  {
    id: "status-review",
    name: "Review",
    color: "#f59e0b",
    scope: "system",
    isDefault: false,
    isCompleted: false,
    order: 3,
    createdAt: new Date("2026-03-31T10:01:00.000Z"),
  },
  {
    id: "status-done",
    name: "Done",
    color: "#22c55e",
    scope: "system",
    isDefault: false,
    isCompleted: true,
    order: 4,
    createdAt: new Date("2026-03-31T10:01:00.000Z"),
  },
]

export const SAMPLE_TASK_PRIORITIES: ITaskPriority[] = [
  {
    id: "priority-low",
    name: "Low",
    color: "#94a3b8",
    level: 1,
    scope: "system",
    isDefault: false,
    createdAt: new Date("2026-03-31T10:01:00.000Z"),
  },
  {
    id: "priority-medium",
    name: "Medium",
    color: "#3b82f6",
    level: 2,
    scope: "system",
    isDefault: true,
    createdAt: new Date("2026-03-31T10:01:00.000Z"),
  },
  {
    id: "priority-high",
    name: "High",
    color: "#f97316",
    level: 3,
    scope: "system",
    isDefault: false,
    createdAt: new Date("2026-03-31T10:01:00.000Z"),
  },
  {
    id: "priority-urgent",
    name: "Urgent",
    color: "#ef4444",
    level: 4,
    scope: "system",
    isDefault: false,
    createdAt: new Date("2026-03-31T10:01:00.000Z"),
  },
]

export const SAMPLE_TASKS: ITask[] = [
  {
    id: "task-1",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Implement Login Flow",
    description:
      "Design and implement the user authentication system using Auth.js and provide proper error handling.",
    type: SAMPLE_TASK_TYPES[0],
    status: SAMPLE_TASK_STATUSES[1],
    priority: SAMPLE_TASK_PRIORITIES[2],
    assigneeId: SAMPLE_PROJECT_MEMBERS[0].id,
    assignee: SAMPLE_PROJECT_MEMBERS[0],
    startDate: new Date("2026-03-31T08:00:00.0Z"),
    dueDate: new Date("2026-04-05T17:00:00.0Z"),
    estimatedHours: 12,
    actualHours: 4,
    createdAt: new Date("2026-03-31T10:01:00.000Z"),
    updatedAt: new Date("2026-03-31T10:01:00.000Z"),
  },
  {
    id: "task-2",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Setup Project Infrastructure",
    description:
      "Initialize the repository, configure linting, and setup CI/CD pipelines for automatic deployment.",
    type: SAMPLE_TASK_TYPES[2],
    status: SAMPLE_TASK_STATUSES[3],
    priority: SAMPLE_TASK_PRIORITIES[1],
    assigneeId: SAMPLE_PROJECT_MEMBERS[1].id,
    assignee: SAMPLE_PROJECT_MEMBERS[1],
    startDate: new Date("2026-03-30T09:00:00.0Z"),
    dueDate: new Date("2026-03-31T17:00:00.0Z"),
    estimatedHours: 8,
    actualHours: 6,
    createdAt: new Date("2026-03-30T10:01:00.000Z"),
    updatedAt: new Date("2026-03-31T09:30:00.000Z"),
  },
  {
    id: "task-3",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Fix Navigation Sidebar Bug",
    description:
      "The sidebar collapes unexpectedly on mobile devices when clicking on a sub-item.",
    type: SAMPLE_TASK_TYPES[1],
    status: SAMPLE_TASK_STATUSES[0],
    priority: SAMPLE_TASK_PRIORITIES[3],
    assigneeId: SAMPLE_PROJECT_MEMBERS[0].id,
    assignee: SAMPLE_PROJECT_MEMBERS[0],
    dueDate: new Date("2026-04-01T12:00:00.0Z"),
    estimatedHours: 4,
    createdAt: new Date("2026-03-31T11:00:00.000Z"),
    updatedAt: new Date("2026-03-31T11:00:00.000Z"),
  },
  {
    id: "task-4",
    projectId: SAMPLE_PROJECTS[0].id,
    title: "Draft Project Documentation",
    description:
      "Create a comprehensive README.md and contributing guidelines for the team.",
    type: SAMPLE_TASK_TYPES[0],
    status: SAMPLE_TASK_STATUSES[1],
    priority: SAMPLE_TASK_PRIORITIES[0],
    assigneeId: SAMPLE_PROJECT_MEMBERS[1].id,
    assignee: SAMPLE_PROJECT_MEMBERS[1],
    startDate: new Date("2026-04-01T13:00:00.0Z"),
    dueDate: new Date("2026-04-03T17:00:00.0Z"),
    estimatedHours: 6,
    createdAt: new Date("2026-03-31T15:20:00.000Z"),
    updatedAt: new Date("2026-03-31T15:20:00.000Z"),
  },
]
