/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardTeamIdRouteImport } from './routes/dashboard/$teamId'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as DashboardTeamIdTeamIndexRouteImport } from './routes/dashboard/$teamId/team/index'
import { Route as DashboardTeamIdProjectsIndexRouteImport } from './routes/dashboard/$teamId/projects/index'
import { Route as DashboardTeamIdOverviewIndexRouteImport } from './routes/dashboard/$teamId/overview/index'
import { Route as DashboardTeamIdMyTasksIndexRouteImport } from './routes/dashboard/$teamId/my-tasks/index'
import { Route as DashboardTeamIdInboxIndexRouteImport } from './routes/dashboard/$teamId/inbox/index'
import { Route as DashboardTeamIdProjectsProjectIdRouteImport } from './routes/dashboard/$teamId/projects/$projectId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamIdRoute = DashboardTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamIdTeamIndexRoute =
  DashboardTeamIdTeamIndexRouteImport.update({
    id: '/team/',
    path: '/team/',
    getParentRoute: () => DashboardTeamIdRoute,
  } as any)
const DashboardTeamIdProjectsIndexRoute =
  DashboardTeamIdProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => DashboardTeamIdRoute,
  } as any)
const DashboardTeamIdOverviewIndexRoute =
  DashboardTeamIdOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => DashboardTeamIdRoute,
  } as any)
const DashboardTeamIdMyTasksIndexRoute =
  DashboardTeamIdMyTasksIndexRouteImport.update({
    id: '/my-tasks/',
    path: '/my-tasks/',
    getParentRoute: () => DashboardTeamIdRoute,
  } as any)
const DashboardTeamIdInboxIndexRoute =
  DashboardTeamIdInboxIndexRouteImport.update({
    id: '/inbox/',
    path: '/inbox/',
    getParentRoute: () => DashboardTeamIdRoute,
  } as any)
const DashboardTeamIdProjectsProjectIdRoute =
  DashboardTeamIdProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/$teamId': typeof DashboardTeamIdRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$teamId/projects/$projectId': typeof DashboardTeamIdProjectsProjectIdRoute
  '/dashboard/$teamId/inbox/': typeof DashboardTeamIdInboxIndexRoute
  '/dashboard/$teamId/my-tasks/': typeof DashboardTeamIdMyTasksIndexRoute
  '/dashboard/$teamId/overview/': typeof DashboardTeamIdOverviewIndexRoute
  '/dashboard/$teamId/projects/': typeof DashboardTeamIdProjectsIndexRoute
  '/dashboard/$teamId/team/': typeof DashboardTeamIdTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/$teamId': typeof DashboardTeamIdRouteWithChildren
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$teamId/projects/$projectId': typeof DashboardTeamIdProjectsProjectIdRoute
  '/dashboard/$teamId/inbox': typeof DashboardTeamIdInboxIndexRoute
  '/dashboard/$teamId/my-tasks': typeof DashboardTeamIdMyTasksIndexRoute
  '/dashboard/$teamId/overview': typeof DashboardTeamIdOverviewIndexRoute
  '/dashboard/$teamId/projects': typeof DashboardTeamIdProjectsIndexRoute
  '/dashboard/$teamId/team': typeof DashboardTeamIdTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/$teamId': typeof DashboardTeamIdRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$teamId/projects/$projectId': typeof DashboardTeamIdProjectsProjectIdRoute
  '/dashboard/$teamId/inbox/': typeof DashboardTeamIdInboxIndexRoute
  '/dashboard/$teamId/my-tasks/': typeof DashboardTeamIdMyTasksIndexRoute
  '/dashboard/$teamId/overview/': typeof DashboardTeamIdOverviewIndexRoute
  '/dashboard/$teamId/projects/': typeof DashboardTeamIdProjectsIndexRoute
  '/dashboard/$teamId/team/': typeof DashboardTeamIdTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/$teamId'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/$teamId/projects/$projectId'
    | '/dashboard/$teamId/inbox/'
    | '/dashboard/$teamId/my-tasks/'
    | '/dashboard/$teamId/overview/'
    | '/dashboard/$teamId/projects/'
    | '/dashboard/$teamId/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/$teamId'
    | '/auth'
    | '/dashboard'
    | '/dashboard/$teamId/projects/$projectId'
    | '/dashboard/$teamId/inbox'
    | '/dashboard/$teamId/my-tasks'
    | '/dashboard/$teamId/overview'
    | '/dashboard/$teamId/projects'
    | '/dashboard/$teamId/team'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/$teamId'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/$teamId/projects/$projectId'
    | '/dashboard/$teamId/inbox/'
    | '/dashboard/$teamId/my-tasks/'
    | '/dashboard/$teamId/overview/'
    | '/dashboard/$teamId/projects/'
    | '/dashboard/$teamId/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$teamId': {
      id: '/dashboard/$teamId'
      path: '/$teamId'
      fullPath: '/dashboard/$teamId'
      preLoaderRoute: typeof DashboardTeamIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$teamId/team/': {
      id: '/dashboard/$teamId/team/'
      path: '/team'
      fullPath: '/dashboard/$teamId/team/'
      preLoaderRoute: typeof DashboardTeamIdTeamIndexRouteImport
      parentRoute: typeof DashboardTeamIdRoute
    }
    '/dashboard/$teamId/projects/': {
      id: '/dashboard/$teamId/projects/'
      path: '/projects'
      fullPath: '/dashboard/$teamId/projects/'
      preLoaderRoute: typeof DashboardTeamIdProjectsIndexRouteImport
      parentRoute: typeof DashboardTeamIdRoute
    }
    '/dashboard/$teamId/overview/': {
      id: '/dashboard/$teamId/overview/'
      path: '/overview'
      fullPath: '/dashboard/$teamId/overview/'
      preLoaderRoute: typeof DashboardTeamIdOverviewIndexRouteImport
      parentRoute: typeof DashboardTeamIdRoute
    }
    '/dashboard/$teamId/my-tasks/': {
      id: '/dashboard/$teamId/my-tasks/'
      path: '/my-tasks'
      fullPath: '/dashboard/$teamId/my-tasks/'
      preLoaderRoute: typeof DashboardTeamIdMyTasksIndexRouteImport
      parentRoute: typeof DashboardTeamIdRoute
    }
    '/dashboard/$teamId/inbox/': {
      id: '/dashboard/$teamId/inbox/'
      path: '/inbox'
      fullPath: '/dashboard/$teamId/inbox/'
      preLoaderRoute: typeof DashboardTeamIdInboxIndexRouteImport
      parentRoute: typeof DashboardTeamIdRoute
    }
    '/dashboard/$teamId/projects/$projectId': {
      id: '/dashboard/$teamId/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/$teamId/projects/$projectId'
      preLoaderRoute: typeof DashboardTeamIdProjectsProjectIdRouteImport
      parentRoute: typeof DashboardTeamIdRoute
    }
  }
}

interface DashboardTeamIdRouteChildren {
  DashboardTeamIdProjectsProjectIdRoute: typeof DashboardTeamIdProjectsProjectIdRoute
  DashboardTeamIdInboxIndexRoute: typeof DashboardTeamIdInboxIndexRoute
  DashboardTeamIdMyTasksIndexRoute: typeof DashboardTeamIdMyTasksIndexRoute
  DashboardTeamIdOverviewIndexRoute: typeof DashboardTeamIdOverviewIndexRoute
  DashboardTeamIdProjectsIndexRoute: typeof DashboardTeamIdProjectsIndexRoute
  DashboardTeamIdTeamIndexRoute: typeof DashboardTeamIdTeamIndexRoute
}

const DashboardTeamIdRouteChildren: DashboardTeamIdRouteChildren = {
  DashboardTeamIdProjectsProjectIdRoute: DashboardTeamIdProjectsProjectIdRoute,
  DashboardTeamIdInboxIndexRoute: DashboardTeamIdInboxIndexRoute,
  DashboardTeamIdMyTasksIndexRoute: DashboardTeamIdMyTasksIndexRoute,
  DashboardTeamIdOverviewIndexRoute: DashboardTeamIdOverviewIndexRoute,
  DashboardTeamIdProjectsIndexRoute: DashboardTeamIdProjectsIndexRoute,
  DashboardTeamIdTeamIndexRoute: DashboardTeamIdTeamIndexRoute,
}

const DashboardTeamIdRouteWithChildren = DashboardTeamIdRoute._addFileChildren(
  DashboardTeamIdRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardTeamIdRoute: typeof DashboardTeamIdRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardTeamIdRoute: DashboardTeamIdRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
